print("Hello World!")
print("My name is Liza")
print("Im 19 years old")
print("Whats about you? Whats your name?")
name_user=input()
print("Hello, Liza. My name is " + name_user)
print("Nice to meet you," + name_user)
print("So,how old are you?")
old_user=input()
print("Im " + old_user + "years old")
print("Ohhh,thats cool!Where you from?")
country_user=input()
print("I am from " + country_user)
print("Wow, me too. Nice to meet you!)
